channels:
  - pytorch
  - conda-forge
  - pypi
dependencies:
  - python==3.7.9
  - stanza==1.2
  - pytorch==1.7.0
  - python-dotenv==0.15.0
  - marshmallow==3.10.0
  - gunicorn==20.0.4
  - pip
  - pip:
      - nauron==1.2
      - estnltk-light==1.6.7.6b0